### ISSUE TITLE
RelayClient, onSubscribe error.

### ISSUE THREAD

**Issue by makinghappen** [WalletConnect/WalletConnectFlutterV2#132]
When trying to connect using example provided:

https://github.com/WalletConnect/WalletConnectFlutterV2#dapp-flow
https://docs.walletconnect.com/2.0/flutter/dapps/dapp-sign-usage

I am getting the following error, and after scanning the connection URI with metamask it does not connect.

flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   RelayClient._onSubscribe (package:walletconnect_flutter_v2/apis/core/relay_client/relay_client.dart:418:19)
flutter: │ #1   <asynchronous suspension>
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ ⚠️ RelayClient, onSubscribe error. Topic: d76177fb912ebd9bead4633152c10b7b2af2e927b398014edd22afcb899036d4, Error: Null check operator used on a null value
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by bobwith2bees** [comment]
Another code path where Metamask is sending nulls?  

Related to #118 since that mentions pairing as well?

**Comment by makinghappen** [comment]
@bobwith2bees this happens before the actual connection with Metamask

**Comment by makinghappen** [comment]
I call initSession and get mentioned error

`class EthereumWallectConnectTransactionV2 {
  late final Web3App wcClient;

  Future<void> initSession() async {
    wcClient = await initWalletConnect();
  }

  Future<Web3App> initWalletConnect() async {
    Web3App wcClient = await Web3App.createInstance(
      relayUrl: 'wss://relay.walletconnect.com', // The relay websocket URL, leave blank to use the default
      projectId: '123',
      metadata: PairingMetadata(
        name: 'dApp (Requester)',
        description: 'A dapp that can request that transactions be signed',
        url: 'https://walletconnect.com',
        icons: ['https://avatars.githubusercontent.com/u/37784886'],
      ),
    );
    return wcClient;
  }

  Future connect() async {
    // Create a new session
    ConnectResponse resp = await wcClient.connect(requiredNamespaces: {
      'eip155': RequiredNamespace(
          chains: ['eip155:1'], // Ethereum chain
          methods: ['eth_signTransaction'], // Requestable Methods
          events: ['']),
    });
    // Uri? uri = resp.uri;

    // final SessionData session = await resp.session.future;
    return resp;
  }
}`

**Comment by Luzzotica** [comment]
Just released 2.0.13 which might resolve this.

Please test and let me know!

**Comment by rkovrigin** [comment]
There is a problem with v2.0.13.
It requires http v1.1.3, and many other libraries depend on lower versions of http, so, that breaks many dependencies =(

**Comment by rkovrigin** [comment]
Tried to fix dependencies and use 2.0.13, have this error now:
#0      _$$_JsonRpcErrorFromJson (package:walletconnect_flutter_v2/apis/models/json_rpc_error.g.dart:11:26)
#1      new _$_JsonRpcError.fromJson (package:walletconnect_flutter_v2/apis/models/json_rpc_error.freezed.dart:115:7)
#2      _$JsonRpcErrorFromJson (package:walletconnect_flutter_v2/apis/models/json_rpc_error.freezed.dart:18:24)
#3      new JsonRpcError.fromJson (package:walletconnect_flutter_v2/apis/models/json_rpc_error.dart:26:7)
#4      _$$_JsonRpcResponseFromJson (package:walletconnect_flutter_v2/apis/models/json_rpc_response.g.dart:18:26)
#5      new _$_JsonRpcResponse.fromJson (package:walletconnect_flutter_v2/apis/models/json_rpc_response.freezed.dart:157:7)
#6      _$JsonRpcResponseFromJson (package:walletconnect_flutter_v2/apis/models/json_rpc_response.freezed.dart:19:10)
#7      new JsonRpcResponse.fromJson (package:walletconnect_flutter_v2/apis/models/json_rpc_response.dart:18:7)
#8      Pairing._onMessageEvent (package:walletconnect_flutter_v2/apis/core/pairing/pairing.dart:656:40)

**Comment by Luzzotica** [comment]
@rkovrigin Please make a separate issue for this http information.

I completely lost it in here, and this issue has _nothing_ to do with an http error.

**Comment by YannMarti** [comment]
I get the same error.
It apppears really inconsistently, so i cant really say how to reproduce, but restarting the app always fixes it temporarily (or the emulator, tried it both in debug mode and as an actuall build on my phone)
