### ISSUE TITLE
Problems creating a function that signs a message

### ISSUE THREAD

**Issue by cheo1894** [WalletConnect/WalletConnectFlutterV2#159]
I am trying to create a function to make a connection with metamask or trust and then make a request in which a message is signed

```
 Future connection() async {
    Web3App wcClient = await Web3App.createInstance(
        // relayUrl: 'wss://relay.walletconnect.com',
        projectId: '1958d35988b449e517442899fd5b9e9a',
        metadata: const PairingMetadata(
            name: 'Test',
            description: 'Conectarme a la wallet',
            url: 'https://walletconnect.com',
            icons: []));

    return wcClient;
  }

  sign() async {
    print('procesando');
    try {
      Web3App wcClient = await connection();
      ConnectResponse resp = await wcClient.connect(requiredNamespaces: {
        'eip155': const RequiredNamespace(chains: [
          'eip155:1'
        ], methods: [
          'personal_sign',
        ], events: [
          "connect",
        ])
      });

      Uri? uri = resp.uri;

      print('======================================= ${uri.toString()}');

      launchUrlString(uri.toString());

      final SessionData session = await resp.session.future;

      print('==============================================${session.toString()}');

      try {
        final signature = await wcClient.request(
          topic: session.topic,
          chainId: 'eip155:1',
          request: const SessionRequestParams(
            method: 'personal_sign',
            params: 5654567,
          ),
        );
        print(" ============================================ ${signature.toString()}");
      } catch (e) {
        print(' ----------------------------------- $e');
      }
    } catch (e) {
      print(e);
    }
  }

```

So far this is the response I've managed to get, I haven't managed to get the signature I need

```

I/flutter (12856): ==============================================SessionData(topic: 001d2996229dc2156494753cead6a2acf6c13252b71083b88150ec863d5aad89, pairingTopic: bcb6a872747e8bf0c628d9938b1bb659336f786e99fb9d3ecb7644c0df1b7453, relay: Instance of 'Relay', expiry: 1691109072, acknowledged: true, controller: 0334373c06a11b27948a17c87f77f31eda67c5dcb4b3893ebcea287c881b7219, namespaces: {eip155: Namespace(accounts: [eip155:1:0xD643d360bd92b00c60763f78aC5f968577049e05], methods: [personal_sign], events: [connect])}, requiredNamespaces: null, optionalNamespaces: null, sessionProperties: null, self: ConnectionMetadata(publicKey: c7900110221ce1ae32e6e053315421898d3edadf949e65c9a346a53f04aedf7c, metadata: PairingMetadata(name: Test, description: Conectarme a la wallet, url: https://walletconnect.com, icons: [], redirect: null)), peer: ConnectionMetadata(publicKey: 0334373c06a11b27948a17c87f77f31eda67c5dcb4b3893ebcea287c881b7219, metadata: PairingMetadata(name: Trust Wallet is a secure and easy-to-use mobile wallet, description: Trust
I/flutter (12856): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (12856): │ #0   Pairing.sendRequest (package:walletconnect_flutter_v2/apis/core/pairing/pairing.dart:388:17)
I/flutter (12856): │ #1   SignEngine.request (package:walletconnect_flutter_v2/apis/sign_api/sign_engine.dart:471:31)
I/flutter (12856): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (12856): │ pairing sendResult, id: null topic: 001d2996229dc2156494753cead6a2acf6c13252b71083b88150ec863d5aad89, method: wc_sessionRequest, params: WcSessionRequestRequest(chainId: eip155:1, request: SessionRequestParams(method: personal_sign, params: 5654567)), ttl: null
```

**Comment by Luzzotica** [comment]
In the example dapp I have the following code to request a personal signature:

```dart
return await web3App.request(
      topic: topic,
      chainId: chainId,
      request: SessionRequestParams(
        method: methods[EIP155Methods.personalSign]!,
        params: [data, address],
      ),
    );
```

Looks to me like your params are incorrect if you're wanting a personal signature, which is why it would fail silently/not show up in MetaMask or Trust wallet.

If the above code resolved your issue, close this issue.

**Comment by cheo1894** [comment]
"métodos[EIP155 Métodos.personalSign]!" es parte de la librería de walletConnect v2

**Comment by cheo1894** [comment]
"methods[EIP155 Methods.personalSign]!" is it part of the walletConnect v2 library?

**Comment by samuel2629** [comment]
I had a similar issue, can you check what network you're on plz? Is that Ethereum Main Network ?

**Comment by Luzzotica** [comment]
> "methods[EIP155 Methods.personalSign]!" is it part of the walletConnect v2 library?

No.
It's in the example app.
WalletConnectV2 is chain agnostic. Any of these methods and their requests you will have to make yourself.

Here is the updated code:

```dart
return await web3App.request(
      topic: topic,
      chainId: chainId,
      request: SessionRequestParams(
        method: 'personal_sign',
        params: [data, address],
      ),
    );
```
