### ISSUE TITLE
Disconnecting an expired pairing throws JsonRpcError 

### ISSUE THREAD

**Issue by bobwith2bees** [WalletConnect/WalletConnectFlutterV2#42]
Looks like a code path in the new clear logic needs to be fixed.  I can clear an active pairing, but when I try to clear an expired paring, it throws a Unhandled Exception: JsonRpcError(code: -32602, message: Expired. 

NOTE: These sessions have been stacking up on my app since the clear logic wasn't working.   Not sure if this will occur with the updated logic.   

```dart
  /// For all core pairings, disconnect
  Future corePairingsDisconnectAll({ICore? core}) async {
    logger.d('clearAllPairings - ');
    core = core ?? _signClient.core;
    // Parings
    List<PairingInfo> parings = core.pairing.getPairings();

    logger.d('==Pairings (${parings.length})==');
    if (parings.isEmpty) {
      logger.d('No Pairings.');
    } else {
      for (PairingInfo pairingInfo in parings) {
        logger.d(
            'Disconnect - ${printDurationFromNow(pairingInfo.expiry)} topic: ${pairingInfo.topic}, relay: ${relayToString(pairingInfo.relay)}, active: ${pairingInfo.active}, ${pairingInfo.peerMetadata?.name ?? 'unavailable'}');
        await core.pairing.disconnect(topic: pairingInfo.topic);
      }
    }
    return;
  }
```

Clearing out my session table:

```
I/flutter (16858): 09:20:14 🐛 WalletConnctSvc - =Core Services (wc v2 crypto - uptime: 127 seconds)=
I/flutter (16858): 09:20:14 🐛 WalletConnctSvc - Relay URL: wss://relay.walletconnect.org
I/flutter (16858): 09:20:14 🐛 WalletConnctSvc - ==Pairings (10)==
I/flutter (16858): 09:20:14 🐛 WalletConnctSvc - <expired> topic: 3c7966ebb41a8c4c21760fa6593ec3d5849efbf30ccd4a9b1d75193699ac1f2b, relay irn, active: false peer: <unavailable>
I/flutter (16858): 09:20:14 🐛 WalletConnctSvc - <expired> topic: 2a08b7f14035cbab2927189c2c8d000938039c50f9ac6a325dc30c73f432f33e, relay irn, active: false peer: <unavailable>
I/flutter (16858): 09:20:14 🐛 WalletConnctSvc - <expired> topic: 8d99ec404ed1c1ebd85b9ae48ff440ad4307d7e9415556b688777cc6593a9b51, relay irn, active: false peer: <unavailable>
I/flutter (16858): 09:20:14 🐛 WalletConnctSvc - <expired> topic: c7b25d40be3ef150572874f00597edb8b587f935be52f1a1e63a17dc410b567d, relay irn, active: false peer: <unavailable>
I/flutter (16858): 09:20:14 🐛 WalletConnctSvc - <expired> topic: 33a8e24dbc35e1958e5ffd9adda9cf1f3bec23a8ebdd3bda605a5c3c790580e3, relay irn, active: false peer: <unavailable>
I/flutter (16858): 09:20:14 🐛 WalletConnctSvc - <expired> topic: 31ca0d6fbe8bd577d44dc37297a1a3dcf2e38bf9598361e9f9a82cfacf3dd6dc, relay irn, active: false peer: <unavailable>
I/flutter (16858): 09:20:14 🐛 WalletConnctSvc - <expired> topic: 6e843d6d2c2c17d522d09355a3c87dc4e9324310e41e1e1d0c60af48fc28935d, relay irn, active: false peer: <unavailable>
I/flutter (16858): 09:20:14 🐛 WalletConnctSvc - 29.1 days topic: 460c68cf332c73cbaf4e7a9758207a17e727a00d5ef47b0388e2136abf8d948d, relay irn, active: true peer: BitKeep
I/flutter (16858): 09:20:14 🐛 WalletConnctSvc - <expired> topic: 9d1f170cef7bb27ef295369a173910d3466f8a8a91eda63a88c83fb0ad0175a5, relay irn, active: false peer: <unavailable>
I/flutter (16858): 09:20:14 🐛 WalletConnctSvc - 29.2 days topic: 0899811f65de9b6a096fcb8c763ff20ee23196b0ec750945745bc3202ce092a6, relay irn, active: true peer: BitKeep
I/flutter (16858): 09:20:38 🐛 WalletConnctSvc - clearAllPairings - 
I/flutter (16858): 09:20:38 🐛 WalletConnctSvc - ==Pairings (10)==
I/flutter (16858): 09:20:38 🐛 WalletConnctSvc - Disconnect - <expired> topic: 3c7966ebb41a8c4c21760fa6593ec3d5849efbf30ccd4a9b1d75193699ac1f2b, relay: irn, active: false, unavailable
E/flutter (16858): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: JsonRpcError(code: -32602, message: Expired. pairing topic: 3c7966ebb41a8c4c21760fa6593ec3d5849efbf30ccd4a9b1d75193699ac1f2b)
E/flutter (16858): #0      Pairing.isValidPairingTopic (package:walletconnect_flutter_v2/apis/core/pairing/pairing.dart:339:7)
E/flutter (16858): <asynchronous suspension>
E/flutter (16858): #1      Pairing._isValidDisconnect (package:walletconnect_flutter_v2/apis/core/pairing/pairing.dart:697:5)
E/flutter (16858): <asynchronous suspension>
E/flutter (16858): #2      Pairing.disconnect (package:walletconnect_flutter_v2/apis/core/pairing/pairing.dart:298:5)
E/flutter (16858): <asynchronous suspension>
E/flutter (16858): #3      WalletConnectService.corePairingsDisconnectAll (package:flutter_web3_demo/services/walletconnect_service.dart:531:9)
E/flutter (16858): <asynchronous suspension>
E/flutter (16858): #4      _MyHomePageState.build.<anonymous closure> (package:flutter_web3_demo/main.dart:237:19)
E/flutter (16858): <asynchronous suspension>
E/flutter (16858): 
```

**Comment by bobwith2bees** [comment]
Note1:
The expired pairing entry (active:false) also shows up in the Sign Client Proposal List.  I suspect to reproduce this you only need to do is initiate pairing, wait 5 minutes then call disconnect on the unpaired topic.

```
I/flutter (19482): 13:38:10 🐛 WalletConnctSvc - relayClientConnect - protocol wc v2 url: wss://relay.walletconnect.org
I/flutter (19482): 13:38:12 🐛 WalletConnctSvc - Core.onRelayClientConnect - Marking relay connection up.
I/flutter (19482): 13:42:18 🐛 WalletConnctSvc - =Core Services (wc v2 crypto - uptime: 246 seconds)=
I/flutter (19482): 13:42:18 🐛 WalletConnctSvc - Relay URL: wss://relay.walletconnect.org
I/flutter (19482): 13:42:18 🐛 WalletConnctSvc - ==Pairings (4)==
I/flutter (19482): 13:42:18 🐛 WalletConnctSvc - 28.9 days topic: 460c68cf332c73cbaf4e7a9758207a17e727a00d5ef47b0388e2136abf8d948d, relay irn, active: true peer: BitKeep
I/flutter (19482): 13:42:18 🐛 WalletConnctSvc - <expired> topic: 9d1f170cef7bb27ef295369a173910d3466f8a8a91eda63a88c83fb0ad0175a5, relay irn, active: false peer: <unavailable>
I/flutter (19482): 13:42:18 🐛 WalletConnctSvc - 29.0 days topic: 0899811f65de9b6a096fcb8c763ff20ee23196b0ec750945745bc3202ce092a6, relay irn, active: true peer: BitKeep
I/flutter (19482): 13:42:18 🐛 WalletConnctSvc - <expired> topic: 68fb06fb7ce4794321e19e7493eb06b4bca7dba735a644ff286f2b623ac1ce91, relay irn, active: false peer: <unavailable>
I/flutter (19482): 13:42:53 🐛 WalletConnctSvc - =Sign Client Info - (wc v2)=
I/flutter (19482): 13:42:53 🐛 WalletConnctSvc - ==Sign Client Sessions (0)==
I/flutter (19482): 13:42:53 🐛 WalletConnctSvc - No sessions.
I/flutter (19482): 13:42:53 🐛 WalletConnctSvc - ==Sign Client Proposals (2)==
I/flutter (19482): 13:42:53 🐛 WalletConnctSvc - <expired> topic: 9d1f170cef7bb27ef295369a173910d3466f8a8a91eda63a88c83fb0ad0175a5 - required: [ eip155:137 ], optional: [  ], session properties: null, id: 1677608096364, relays: [ irn ]
I/flutter (19482): 13:42:53 🐛 WalletConnctSvc - <expired> topic: 68fb06fb7ce4794321e19e7493eb06b4bca7dba735a644ff286f2b623ac1ce91 - required: [ eip155:137 ], optional: [  ], session properties: null, id: 1677685680833, relays: [ irn ]
I/flutter (19482): 13:42:53 🐛 WalletConnctSvc - ==Sign Client Stats==
I/flutter (19482): 13:42:53 🐛 WalletConnctSvc - No data.
I/flutter (19482): 13:43:12 🐛 WalletConnctSvc - Core.onRelayClientDisconnect - Marking relay connection down. Connection lasted 300 seconds.
I/flutter (19482): 13:43:12 ⚠️ WalletConnctSvc - Core.onRelayClientDisconnect - Attempt relayClientConnect() to recover. (isRelayClientEnabled = true, Retry Count: 44)
I/flutter (19482): 13:43:12 🐛 WalletConnctSvc - relayClientConnect - protocol wc v2 url: wss://relay.walletconnect.org
I/flutter (19482): 13:43:13 🐛 WalletConnctSvc - Core.onRelayClientConnect - Marking relay connection up.
I/flutter (19482): 13:43:51 🐛 WalletConnctSvc - clearAllPairings - 
I/flutter (19482): 13:43:51 🐛 WalletConnctSvc - ==Pairings (4)==
I/flutter (19482): 13:43:51 🐛 WalletConnctSvc - Disconnect - 28.9 days topic: 460c68cf332c73cbaf4e7a9758207a17e727a00d5ef47b0388e2136abf8d948d, relay: irn, active: true, BitKeep
I/flutter (19482): 13:43:51 🐛 WalletConnctSvc - Disconnect - <expired> topic: 9d1f170cef7bb27ef295369a173910d3466f8a8a91eda63a88c83fb0ad0175a5, relay: irn, active: false, unavailable
E/flutter (19482): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: JsonRpcError(code: -32602, message: Expired. pairing topic: 9d1f170cef7bb27ef295369a173910d3466f8a8a91eda63a88c83fb0ad0175a5)
E/flutter (19482): #0      Pairing.isValidPairingTopic (package:walletconnect_flutter_v2/apis/core/pairing/pairing.dart:339:7)
E/flutter (19482): <asynchronous suspension>
E/flutter (19482): #1      Pairing._isValidDisconnect (package:walletconnect_flutter_v2/apis/core/pairing/pairing.dart:697:5)
```


Note2:
The session does get disconnected, but I am not sure what logic might not be completed.  My loop certainly exits early.

**Comment by Luzzotica** [comment]
Is this still occurring with the most recent version (1.1.2? I made some updates to error handling in the library. 
If it still occurs, I'll double check things.

**Comment by bobwith2bees** [comment]
Yes it still occurs.   I was able to reproduce it by pairing a wallet, waiting for the pairing proposal to expire, then call disconnect.

NOTE: The expired pairing is has the same topic as the sign client proposal.  It is marked active:false as the negotiated connection has a new topic string.  Maybe there is cleanup that isn't occurring on this temporary pairing topic? 

## Workaround ##
Do not call disconnect if the pairing if (active == false).  

```
flutter: 10:02:39 🐛 WalletConnctSvc - =Core Services (wc v2 crypto - uptime: 82 seconds)=
flutter: 10:02:39 🐛 WalletConnctSvc - Relay URL: wss://relay.walletconnect.org
flutter: 10:02:39 🐛 WalletConnctSvc - ==Pairings (2)==
flutter: 10:02:39 🐛 WalletConnctSvc - <expired> topic: 82a2965bdaf216e6300ea9a2756e6d08f979a979892cecacc073118b728c639a, relay irn, active: false peer: <unavailable>
flutter: 10:02:39 🐛 WalletConnctSvc - 30.0 days topic: f1f466b146be695b54cbd30f46e6c5dbcdb929e442e0ffae0d05108a92ea19ae, relay irn, active: true peer: Keyring
flutter: 10:02:40 🐛 WalletConnctSvc - =Sign Client Info - (wc v2)=
flutter: 10:02:40 🐛 WalletConnctSvc - ==Sign Client Sessions (1)==
flutter: 10:02:40 🐛 WalletConnctSvc -  7.0 days topic: 0f3a56e4a05a0ccae857cc2eba8bfe80fb1fc85b576925912434e2a4a6a3e808, pairing topic: f1f466b146be695b54cbd30f46e6c5dbcdb929e442e0ffae0d05108a92ea19ae ack: true, peer name: Keyring accounts: [ eip155:137:0x0a639a9dd60d699c2cb4219082e26a4180b5263d ]
flutter: 10:02:40 🐛 WalletConnctSvc - ==Sign Client Proposals (1)==
flutter: 10:02:40 🐛 WalletConnctSvc - <expired> topic: 82a2965bdaf216e6300ea9a2756e6d08f979a979892cecacc073118b728c639a - required: [ eip155:137 ], optional: [  ], session properties: null, id: 1677945849000, relays: [ irn ]
flutter: 10:02:40 🐛 WalletConnctSvc - ==Sign Client Stats==
flutter: 10:02:40 🐛 WalletConnctSvc - 
Sign Client topic: 0f3a56e4a05a0ccae857cc2eba8bfe80fb1fc85b576925912434e2a4a6a3e808 - messageCount: 0 (0 bytes), errorCount 0, pings(TX/RX): 0/0, expireCount: 0, extentCount: 0, connectTime: 09:57:52, deleteTime:  unknown
flutter: 10:02:47 🐛 WalletConnctSvc - clearAllPairings -
flutter: 10:02:47 🐛 WalletConnctSvc - ==Pairings (2)==
flutter: 10:02:47 🐛 WalletConnctSvc - Disconnect - <expired> topic: 82a2965bdaf216e6300ea9a2756e6d08f979a979892cecacc073118b728c639a, relay: irn, active: false, unavailable
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: JsonRpcError(code: -32602, message: Expired. pairing topic: 82a2965bdaf216e6300ea9a2756e6d08f979a979892cecacc073118b728c639a)
#0      Pairing.isValidPairingTopic (package:walletconnect_flutter_v2/apis/core/pairing/pairing.dart:339:7)
<asynchronous suspension>
#1      Pairing._isValidDisconnect (package:walletconnect_flutter_v2/apis/core/pairing/pairing.dart:692:5)
<asynchronous suspension>
#2      Pairing.disconnect (package:walletconnect_flutter_v2/apis/core/pairing/pairing.dart:298:5)
<asynchronous suspension>
#3      WalletConnectService.disconnectAllParings (package:flutter_web3_demo/services/walletconnect_service.dart:577:11)
<asynchronous suspension>
#4      _MyHomePageState.build.<anonymous closure> (package:flutter_web3_demo/main.dart:126:21)
<asynchronous suspension>
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
```

**Comment by Luzzotica** [comment]
If you wrap your `disconnect` in a try catch, does that work?

It's actually supposed to throw the expired error.

You just need to handle it accordingly.

It's safe enough to ignore it.

**Comment by bobwith2bees** [comment]
Much of the time with the JsonRpcErrors I am seeing:

 1) The asynchronous method has returned and code has continued passed the try/catch before the error occurs.   
 
 2) I have tried widening the try/catch, but there also seem to be issues with the JsonRpcErrors not getting re-thrown so they are catch-able.

**Comment by Luzzotica** [comment]
The JsonRpcErrors nor WalletConnectError are exceptions. 
So your try/catch in the code above wouldn't catch them.

Instead of `on Exception`, just do a generic `catch (e)` to catch all thrown errors.

If you do that, and the issue persists, let me know.
When you disconnect, and the pairing has expired, it should automatically be deleted. 
I suppose the fact that they aren't deleted for you is worrisome... I haven't experienced this in my example dApp.

**Comment by Luzzotica** [comment]
#43 Changes the `JsonRpcError` to be a `WalletConnectError`.

If wrapping the disconnect with a try/catch that is looking for a `WalletConnectError` doesn't work, keep this issue open.
If it does work, please close this issue out.

**Comment by bobwith2bees** [comment]
Tested against repo sha 78a982e

1. Confirmed the issue can be caught with a WalletConnectError and I can just log this as a warning. 
2. Thanks for wrapping it in a WalletConnect error.  
3. I'll keep an eye on the growing size of core.pairing.getPairings() and signClient.sessions.getAll(). 

For the next developer - this code is improved:
```dart
        try {
          await core.pairing.disconnect(topic: pairingInfo.topic);
        } on WalletConnectError catch (e) {
         // technically look for WalletConnectError 6 : Expired.  to consider it a warning
          logger.w('disconnectAllParings - WalletConnectError ${e.code} : ${e.message}');
        } catch (e, s) {
        // Catch anything else (not just Exceptions) and log stack
          logger.e('disconnectAllParings - Unexpected error: $e, topic ${pairingInfo.topic}\n$s');
        }
```
