### ISSUE TITLE
Relay reconnect logic throws unhandled Null check

### ISSUE THREAD

**Issue by bobwith2bees** [WalletConnect/WalletConnectFlutterV2#76]
The first time a Relay Client session is automatically re-connected, there is a null assertion fired.  Follow on re-connects are fine.   (This may be causing some flakiness for app user's minutes 5-10. )

NOTE: This may have been introduced in the 2.0 timeframe, not new with today's build.

Steps to reproduce:

1. Connect a new Wallet
2. Navigate back to the flutter app
3. Wait for 5 minutes for the onRelayClientDisconnect event to occur.

_createJsonRPCProvider
```dart
      jsonRPC = Peer(socket.channel!);
```

```
I/flutter (24464): 18:57:53 🐛 HomePage        - AppLifecycleState: AppLifecycleState.resumed.
I/flutter (24464): 18:58:52 🐛 WalletConnctSvc - Core.onRelayClientDisconnect - Marking relay connection down. Connection lasted 299 seconds.
I/flutter (24464): 18:58:53 🐛 WalletConnctSvc - Core.onRelayClientError  - error: Null check operator used on a null value
E/flutter (24464): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (24464): #0      RelayClient._createJsonRPCProvider (package:walletconnect_flutter_v2/apis/core/relay_client/relay_client.dart:215:36)
E/flutter (24464): <asynchronous suspension>
E/flutter (24464): #1      RelayClient.connect (package:walletconnect_flutter_v2/apis/core/relay_client/relay_client.dart:176:5)
E/flutter (24464): <asynchronous suspension>
E/flutter (24464): #2      RelayClient._reconnect (package:walletconnect_flutter_v2/apis/core/relay_client/relay_client.dart:246:5)
E/flutter (24464): <asynchronous suspension>
E/flutter (24464): 
I/flutter (24464): 18:58:53 🐛 WalletConnctSvc - Core.onRelayClientConnect - Marking relay connection up.
```
Later reconnects work without error.  
```
I/flutter (24464): 19:03:53 🐛 WalletConnctSvc - Core.onRelayClientDisconnect - Marking relay connection down. Connection lasted 299 seconds.
I/flutter (24464): 19:03:55 🐛 WalletConnctSvc - Core.onRelayClientConnect - Marking relay connection up.
I/flutter (24464): 19:08:55 🐛 WalletConnctSvc - Core.onRelayClientDisconnect - Marking relay connection down. Connection lasted 300 seconds.
I/flutter (24464): 19:08:56 🐛 WalletConnctSvc - Core.onRelayClientConnect - Marking relay connection up
```

If you restart the app (with the saved connection) there is a more dramatic failure mode on first reconnect.  Same/different issue?:
```
I/flutter (30782): 19:20:05 🐛 WalletConnctSvc - Core.onRelayClientDisconnect - Marking relay connection down. Connection lasted 299 seconds.
I/flutter (30782): 19:20:07 🐛 WalletConnctSvc - Core.onRelayClientConnect - Marking relay connection up.
I/flutter (30782): 19:20:07 ⛔ WalletConnctSvc - Core.onRelayClientError  - error: Bad state: Stream has already been listened to.
E/flutter (30782): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Stream has already been listened to.
E/flutter (30782): #0      _StreamController._subscribe (dart:async/stream_controller.dart:676:7)
E/flutter (30782): #1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827:19)
E/flutter (30782): #2      _StreamImpl.listen (dart:async/stream_impl.dart:471:9)
E/flutter (30782): #3      _WebSocketImpl.listen (dart:_http/websocket_impl.dart:1188:31)
E/flutter (30782): #4      _CompleterStream.listen (package:async/src/stream_completer.dart:127:29)
E/flutter (30782): #5      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
E/flutter (30782): #6      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
E/flutter (30782): #7      _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
E/flutter (30782): #8      CastStream.listen (dart:_internal/async_cast.dart:17:17)
E/flutter (30782): #9      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
E/flutter (30782): #10     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
E/flutter (30782): #11     _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
E/flutter (30782): #12     _CloseGuaranteeStream.listen (package:stream_channel/src/close_guarantee_channel.dart:60:31)
E/flutter (30782): #13     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
E/flutter (30782): #14     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
E/flutter (30782): #15     _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
E/flutter (30782): #16     _CloseGuaranteeStream.listen (package:stream_channel/src/close_guarantee_channel.dart:60:31)
E/flutter (30782): #17     Peer.listen (package:walletconnect_flutter_v2/apis/core/relay_client/json_rpc_2/src/peer.dart:123:21)
E/flutter (30782): #18     RelayClient._createJsonRPCProvider (package:walletconnect_flutter_v2/apis/core/relay_client/relay_client.dart:230:15)
E/flutter (30782): <asynchronous suspension>
E/flutter (30782): #19     RelayClient.connect (package:walletconnect_flutter_v2/apis/core/relay_client/relay_client.dart:176:5)
E/flutter (30782): <asynchronous suspension>
E/flutter (30782): #20     RelayClient._reconnect (package:walletconnect_flutter_v2/apis/core/relay_client/relay_client.dart:246:5)
E/flutter (30782): <asynchronous suspension>
I/flutter (30782): 19:25:07 🐛 WalletConnctSvc - Core.onRelayClientDisconnect - Marking relay connection down. Connection lasted 300 seconds.
I/flutter (30782): 19:29:56 🐛 HomePage        - Ping Pairing BitKeep
I/flutter (30782): 19:29:56 🐛 WalletConnctSvc - pingPairing - topic: 031a9eb332dfdb563c081c05bed258dd1d55cbd104514a0cd3909bba8ec7c3d7
I/flutter (30782): 19:29:56 ⛔ WalletConnctSvc - Core.onRelayClientError  - error: Bad state: Cannot add event after closing
```
The reconnection logic does not fire.

**Comment by bobwith2bees** [comment]
I tried with a different wallet (Rainbow for Android.)  The behavior looks more like a race condition.  It didn't occur on the first reconnect.

### Steps 

1. Start App
2. Connect wallet
3. Wait

```
I/flutter (23748): 10:39:39 🐛 WalletConnctSvc - Core.onRelayClientDisconnect - Marking relay connection down. Connection lasted 300 seconds.
I/flutter (23748): 10:39:40 🐛 WalletConnctSvc - Core.onRelayClientConnect - Marking relay connection up.
I/flutter (23748): 10:44:40 🐛 WalletConnctSvc - Core.onRelayClientDisconnect - Marking relay connection down. Connection lasted 299 seconds.
I/flutter (23748): 10:44:43 🐛 WalletConnctSvc - Core.onRelayClientConnect - Marking relay connection up.
I/flutter (23748): 10:49:43 🐛 WalletConnctSvc - Core.onRelayClientDisconnect - Marking relay connection down. Connection lasted 300 seconds.
I/flutter (23748): 10:49:45 ⛔ WalletConnctSvc - Core.onRelayClientError  - error: Null check operator used on a null value
E/flutter (23748): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (23748): #0      RelayClient._createJsonRPCProvider (package:walletconnect_flutter_v2/apis/core/relay_client/relay_client.dart:215:36)
E/flutter (23748): <asynchronous suspension>
E/flutter (23748): #1      RelayClient.connect (package:walletconnect_flutter_v2/apis/core/relay_client/relay_client.dart:176:5)
E/flutter (23748): <asynchronous suspension>
E/flutter (23748): #2      RelayClient._reconnect (package:walletconnect_flutter_v2/apis/core/relay_client/relay_client.dart:246:5)
E/flutter (23748): <asynchronous suspension>
E/flutter (23748): 
I/flutter (23748): 10:49:45 🐛 WalletConnctSvc - Core.onRelayClientConnect - Marking relay connection up.
```

**Comment by bobwith2bees** [comment]
Looks good.  I did hit a corner case ... because I am cursed at hitting bugs.   

I was disconnecting the pairing on my side, when the relay connection went down.  The restart logic I think threw a few errors when the disconnect logic was trying to delete the sessions associated with the pairing.


disconnectPairing is my function that calls 
```dart
await core.pairing.disconnect(topic: topic);
```
```
I/flutter (15052): 10:26:14 🐛 WalletConnctSvc - disconnectPairing - 
I/flutter (15052): 10:26:16 🐛 WalletConnctSvc - Core.onRelayClientDisconnect - Marking relay connection down. Connection lasted 298 seconds.
I/flutter (15052): 10:26:17 🐛 WalletConnctSvc - Core.onRelayClientConnect - Marking relay connection up.
I/flutter (15052): 10:26:17 ⛔ WalletConnctSvc - Core.onRelayClientError  - error: Bad state: Stream has already been listened to.
I/flutter (15052): 10:26:17 ⛔ WalletConnctSvc - Core.onRelayClientError  - error: Bad state: Stream has already been listened to.
I/flutter (15052): 10:26:18 🐛 WalletConnctSvc - signEngine.onSessionDelete  - topic: e9585d7d9b2815f84abe870b9b2f0d3e533892c2ed3a074f63140e1ed4b5cb5b id: null
I/flutter (15052): 10:31:17 🐛 WalletConnctSvc - Core.onRelayClientDisconnect - Marking relay connection down. Connection lasted 300 seconds.
```

**Comment by Luzzotica** [comment]
I appreciate it. I'll write it down in the list of things to tackle.

I'll keep this issue closed, as it looks like the above issue is separate or new, and no longer the null check.
